Repository jimkanman/BagAMoment-Server, pull requests merged in 2024-11, with the labels that each got.

#20 feat: 보관소 API
  build.gradle
  src/main/java/com/jkm/jimkanman/client/geocoding/GeocodingAdapter.java
  src/main/java/com/jkm/jimkanman/client/geocoding/GoogleGeocodingClient.java
  src/main/java/com/jkm/jimkanman/client/geocoding/VWorldClient.java
  src/main/java/com/jkm/jimkanman/config/ObjectMapperConfig.java
  src/main/java/com/jkm/jimkanman/controller/MemberController.java
  src/main/java/com/jkm/jimkanman/controller/StorageController.java
  src/main/java/com/jkm/jimkanman/converter/StorageOptionConverter.java
  src/main/java/com/jkm/jimkanman/domain/Coordinate.java
  src/main/java/com/jkm/jimkanman/domain/Luggage.java
  src/main/java/com/jkm/jimkanman/domain/Member.java
  src/main/java/com/jkm/jimkanman/domain/Storage.java
  src/main/java/com/jkm/jimkanman/domain/StorageImage.java
  src/main/java/com/jkm/jimkanman/domain/StorageReservation.java
  src/main/java/com/jkm/jimkanman/domain/enums/LuggageType.java
  src/main/java/com/jkm/jimkanman/dto/MemberResponse.java
  src/main/java/com/jkm/jimkanman/dto/ReservationRequest.java
  src/main/java/com/jkm/jimkanman/dto/ReservationResponse.java
  src/main/java/com/jkm/jimkanman/dto/StorageRequest.java
  src/main/java/com/jkm/jimkanman/dto/StorageResponse.java
  src/main/java/com/jkm/jimkanman/repository/LuggageRepository.java
  src/main/java/com/jkm/jimkanman/repository/StorageImageRepository.java
  src/main/java/com/jkm/jimkanman/repository/StorageRegistrationRepository.java
  src/main/java/com/jkm/jimkanman/repository/StorageRepository.java
  src/main/java/com/jkm/jimkanman/repository/StorageReservationRepository.java
  src/main/java/com/jkm/jimkanman/service/DiskFileService.java
  src/main/java/com/jkm/jimkanman/service/FileService.java
  src/main/java/com/jkm/jimkanman/service/MemberService.java
  src/main/java/com/jkm/jimkanman/service/MemberServiceImpl.java
  src/main/java/com/jkm/jimkanman/service/StorageService.java
  src/main/java/com/jkm/jimkanman/service/StorageServiceImpl.java
  src/main/java/com/jkm/jimkanman/util/GpsUtil.java
  src/main/java/com/jkm/jimkanman/util/GpsUtilImpl.java
  src/main/java/com/jkm/jimkanman/util/SecurityUtil.java
  src/test/java/com/jkm/jimkanman/client/geocoding/GoogleGeocodingClientTest.java
  src/test/java/com/jkm/jimkanman/client/geocoding/VWorldClientTest.java
  src/test/java/com/jkm/jimkanman/service/StorageServiceImplTest.java
Labels: enhancement, feat

#45 feat/search-api/42 보관소 검색 기능 구현
  build.gradle
  src/main/java/com/jkm/jimkanman/controller/StorageController.java
  src/main/java/com/jkm/jimkanman/repository/StorageRepository.java
  src/main/java/com/jkm/jimkanman/service/StorageService.java
  src/main/java/com/jkm/jimkanman/service/StorageServiceImpl.java
  src/test/java/com/jkm/jimkanman/service/StorageServiceImplTest.java
Labels: feat

#48 #41 StorageOption Mapping 변경
  build.gradle
  src/main/java/com/jkm/jimkanman/dto/StorageRequest.java
  src/main/java/com/jkm/jimkanman/service/StorageServiceImpl.java
  src/test/java/com/jkm/jimkanman/service/StorageServiceImplTest.java
Labels: bug
